import type { Metadata } from 'next'
import './global.css'
import Navigation from '../components/navigation/navigation'
import Footer from '../components/footer/footer'
import Search from '../components/search/search'

export const metadata: Metadata = {
  title: 'MundoDev',
  description: 'Generated by create next'
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='pt-br'>
      <body suppressHydrationWarning={true}>
        <Navigation />
        <main className='myMain'>
          {children}
          <Search />
        </main>
        <Footer />
      </body>
    </html>
  )
}
